### ISSUE TITLE
Consider setting the default for returnNull to false in next major version (v23.0.0)

### ISSUE THREAD

**Issue by adrai** [i18next/i18next#1884]
Seems for TypeScript users (in combination with react) it would be better to set the `returnNull` value to `false` by default.

https://github.com/i18next/react-i18next/issues/1559
https://github.com/i18next/react-i18next/issues/1576
https://github.com/i18next/react-i18next/issues/1574
https://github.com/i18next/next-i18next/issues/1795
https://github.com/i18next/next-i18next/issues/2038
https://github.com/i18next/next-i18next/issues/2059
https://stackoverflow.com/questions/70914886/react-i18n-t-function-doesnt-accept-string-variables-typescript-no-over/74817767
https://stackoverflow.com/questions/74146925/im-having-issues-with-i18next-in-react-18/74811575
https://stackoverflow.com/questions/74143213/how-to-handle-i18next-new-type-defaulttfuncreturn/74808715

Let's keep `returnEmptyString` set to `true` by default (not necessary regarding TypeScript issues)

<img width="783" alt="image" src="https://user-images.githubusercontent.com/1086194/207426283-26428633-6554-4ed3-a0e7-3225048ce490.png">

I would say as soon as @pedrodurek reviewed (and maybe corrected/optimized) the latest TypeScript changes and issues, we'll go for a new major release that changes the defaults, this would maybe simplify the usage for TypeScript users.
## TODO before next major release
- [ ] verify t function changes, especially regarding performance: https://github.com/i18next/i18next/compare/v22.3.0...master
- [ ] check if those changes are ok for react-i18next
- [ ] also check if this was ok: https://github.com/i18next/i18next/pull/1878
- [ ] recheck https://github.com/i18next/react-i18next/issues?q=is%3Aissue+is%3Aopen+label%3Atypescript
- [ ] recheck https://github.com/i18next/i18next/issues?q=is%3Aissue+is%3Aopen+label%3Atypescript
- [ ] recheck https://github.com/i18next/next-i18next/issues?q=is%3Aissue+is%3Aopen+label%3Atypescript
- [ ] is there also a solution for https://github.com/i18next/next-13-app-dir-i18next-example-ts/blob/main/app/i18n/index.ts#L26 ?

## TODO
- [x] PR #1885 
- [x] merge PR #1885 
- [ ] docs changes: https://www.i18next.com/overview/configuration-options#translation-defaults and https://www.i18next.com/overview/typescript
- [x] also merge PR #1945 for next major
- [x] maybe also consider #1948 for next major
- [x] and if #1948 also remove the isIE stuff
- [x] remove the setDebug function in the logger https://github.com/i18next/i18next/issues/1954#issuecomment-1537117407

**Comment by pedrodurek** [comment]
Hey @adrai, I'll wrap up the remaining work this week.

**Comment by adrai** [comment]
@pedrodurek ?

**Comment by pedrodurek** [comment]
Sorry @adrai, I'll wrap up everything today

**Comment by adrai** [comment]
@pedrodurek are you ok?

**Comment by adrai** [comment]
most of it already in master branch... just waiting for https://github.com/i18next/i18next/pull/1911#issuecomment-1583971620
